//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyCluster.WebService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ClusterNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClusterNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartyCluster.WebService.Resources.ClusterNames", typeof(ClusterNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omega Cluster.
        /// </summary>
        internal static string Name0 {
            get {
                return ResourceManager.GetString("Name0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Cluster.
        /// </summary>
        internal static string Name1 {
            get {
                return ResourceManager.GetString("Name1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kappa Cluster.
        /// </summary>
        internal static string Name10 {
            get {
                return ResourceManager.GetString("Name10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambda Cluster.
        /// </summary>
        internal static string Name11 {
            get {
                return ResourceManager.GetString("Name11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mu Cluster.
        /// </summary>
        internal static string Name12 {
            get {
                return ResourceManager.GetString("Name12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu Cluster.
        /// </summary>
        internal static string Name13 {
            get {
                return ResourceManager.GetString("Name13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xi Cluster.
        /// </summary>
        internal static string Name14 {
            get {
                return ResourceManager.GetString("Name14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omicron Cluster.
        /// </summary>
        internal static string Name15 {
            get {
                return ResourceManager.GetString("Name15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pi Cluster.
        /// </summary>
        internal static string Name16 {
            get {
                return ResourceManager.GetString("Name16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rho Cluster.
        /// </summary>
        internal static string Name17 {
            get {
                return ResourceManager.GetString("Name17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma Cluster.
        /// </summary>
        internal static string Name18 {
            get {
                return ResourceManager.GetString("Name18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tau Cluster.
        /// </summary>
        internal static string Name19 {
            get {
                return ResourceManager.GetString("Name19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta Cluster.
        /// </summary>
        internal static string Name2 {
            get {
                return ResourceManager.GetString("Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upsilon Cluster.
        /// </summary>
        internal static string Name20 {
            get {
                return ResourceManager.GetString("Name20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phi Cluster.
        /// </summary>
        internal static string Name21 {
            get {
                return ResourceManager.GetString("Name21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi Cluster.
        /// </summary>
        internal static string Name22 {
            get {
                return ResourceManager.GetString("Name22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psi Cluster.
        /// </summary>
        internal static string Name23 {
            get {
                return ResourceManager.GetString("Name23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma Cluster.
        /// </summary>
        internal static string Name3 {
            get {
                return ResourceManager.GetString("Name3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta Cluster.
        /// </summary>
        internal static string Name4 {
            get {
                return ResourceManager.GetString("Name4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epsilon Cluster.
        /// </summary>
        internal static string Name5 {
            get {
                return ResourceManager.GetString("Name5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeta Cluster.
        /// </summary>
        internal static string Name6 {
            get {
                return ResourceManager.GetString("Name6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eta Cluster.
        /// </summary>
        internal static string Name7 {
            get {
                return ResourceManager.GetString("Name7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theta Cluster.
        /// </summary>
        internal static string Name8 {
            get {
                return ResourceManager.GetString("Name8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iota Cluster.
        /// </summary>
        internal static string Name9 {
            get {
                return ResourceManager.GetString("Name9", resourceCulture);
            }
        }
    }
}
